datatype: charades
train_csv: data/charades_pkl/Charades_v1_train.csv
val_csv: data/charades_pkl/Charades_v1_test.csv
data_path: data/charades_pkl/charades.json
features_path: data/charades_pkl/Charades_v1_features_rgb_1024
init_model: weights/weight/univl.pretrained.bin
output_dir: ckpts/ckpt_charades_localization_univl_baseline

do_train: True
do_pretrain: False
do_eval: False

task_type: localization
summ_type: None
epochs: 5
batch_size: 32
lr: 0.001
coef_lr: 0.1
margin: 0.1
max_words: 32
max_frames: 32
batch_size_val: 32
video_dim: 1024
feature_framerate: 1

bert_model: bert-base-uncased
visual_model: visual-base
cross_model: cross-base
decoder_model: decoder-base
do_lower_case: True
text_num_hidden_layers: 12
visual_num_hidden_layers: 6
cross_num_hidden_layers: 2
decoder_num_hidden_layers: 3

max_signal: 100
n_pair: 1
negative_weighting: 1
hard_negative_rate: 0.5
use_mil: True
num_thread_reader: 4
gradient_accumulation_steps: 1
warmup_proportion: 0.1
n_display: 100

n_gpu: 4
local_rank: 0
world_size: 0

stage_two: True
seed: 0

cache_dir: False

defaults:
  - configs/audio-config
  - configs/audio-cross-config
  - configs/bert-config
  - configs/cross-config
  - configs/decoder-config
  - configs/i3d-config
  - configs/visual-config
