train_csv: data/data/HowTo100M.csv
data_path: data/data/caption.pickle
features_path: data/data/HowTo100M/howto100m_s3d_features
init_model: <from first stage>
output_dir: models/pre_trained/L48_V6_D3_Phase2

do_train: False
do_pretrain: True
do_eval: False

task_type: pretrain
summ_type: sampling
epochs: 50
batch_size: 80
lr: 0.0001
coef_lr: 0.1
margin: 0.1
min_words: 0
max_words: 48
max_frames: 64
batch_size_val: 80
video_dim: 1024
feature_framerate: 1
min_time: 5.0

bert_model: bert-base-uncased
visual_model: visual-base
cross_model: cross-base
decoder_model: decoder-base
do_lower_case: True
text_num_hidden_layers: 12
visual_num_hidden_layers: 6
cross_num_hidden_layers: 2
decoder_num_hidden_layers: 3

max_signal: 100
n_pair: 3
negative_weighting: 1
hard_negative_rate: 0.5
use_mil: True
sampled_use_mil: True
num_thread_reader: 0
gradient_accumulation_steps: 60
warmup_proportion: 0.1
lr_decay: 0.9
n_display: 100

n_gpu: 1
local_rank: 0
world_size: 0

stage_two: True
pretrain_enhance_vmodal: True
seed: 42

cache_dir: False
fp16: False
fp16_opt_level: '01'

load_checkpoint: True
checkpoint_model: 'pytorch_model.bin.checkpoint'

defaults:
  - configs/audio-config
  - configs/audio-cross-config
  - configs/bert-config
  - configs/cross-config
  - configs/decoder-config
  - configs/i3d-config
  - configs/visual-config
