DATATYPE: msrvtt
TRAIN_CSV: data/msrvtt/MSRVTT_train.9k.csv
VAL_CSV: data/msrvtt/MSRVTT_JSFUSION_test.csv
DATA_PATH: data/msrvtt/MSRVTT_data.json
FEATURES_PATH: data/msrvtt/msrvtt_videos_features.pickle
INIT_MODEL: weight/univl.pretrained.bin
OUTPUT_ROOT: ckpts

datatype: msrvtt
output_dir: ckpts/ckpt_msrvtt_retrieval
train_csv: data/msrvtt/MSRVTT_train.9k.csv
val_csv: data/msrvtt/MSRVTT_JSFUSION_test.csv
data_path: data/msrvtt/MSRVTT_data.json
features_path: data/msrvtt/msrvtt_videos_features.pickle
init_model: weight/univl.pretrained.bin

do_pretrain: True
do_train: True
do_eval: True
num_thread_reader: 1
lr: 0.0001
epochs: 20
batch_size: 256

batch_size_val: 3500
lr_decay: 0.9
n_display: 100
video_dim: 1024
seed: 42
max_words: 20
max_frames: 100

feature_framerate: 1
margin: 0.1
hard_negative_rate: 0.5
negative_weighting: 1
n_pair: 1
bert_model: bert-base-uncased
visual_model: visual-base

cross_model: cross-base
decoder_model: decoder-base
do_lower_case: True
warmup_proportion: 0.1
gradient_accumulation_steps: 1
n_gpu: 1
cache_dir: ""

fp16: True
fp16_opt_level: '01'
task_type: retrieval
world_size: 0
local_rank: 0
coef_lr: 0.1
use_mil: True

sampled_use_mil: True
text_num_hidden_layers: 12
visual_num_hidden_layers: 6
cross_num_hidden_layers: 2
decoder_num_hidden_layers: 3
train_sim_after_cross: True
expand_msrvtt_sentences: True