datatype: msrvtt
train_csv: data/msrvtt/MSRVTT_train.9k.csv
val_csv: data/msrvtt/MSRVTT_JSFUSION_test.csv
data_path: data/msrvtt/MSRVTT_data.json
features_path: data/msrvtt/summ/msrvtt_videos_features_naive_50.pickle
init_model: weights/weight/univl.pretrained.bin
output_dir: ckpts/summ/ckpt_msrvtt_caption_naive_50

do_train: True
do_pretrain: False
do_eval: False

task_type: caption
epochs: 5
batch_size: 128
lr: 0.00005
coef_lr: 0.1
margin: 0.1
max_words: 48
max_frames: 48
batch_size_val: 32
video_dim: 1024
feature_framerate: 1

bert_model: bert-base-uncased
visual_model: visual-base
cross_model: cross-base
decoder_model: decoder-base
do_lower_case: True
text_num_hidden_layers: 12
visual_num_hidden_layers: 6
cross_num_hidden_layers: 2
decoder_num_hidden_layers: 3

max_signal: 100
n_pair: 1
negative_weighting: 1
hard_negative_rate: 0.5
use_mil: True
num_thread_reader: 16
gradient_accumulation_steps: 1
warmup_proportion: 0.1
n_display: 100

n_gpu: 1
local_rank: 0
world_size: 0

stage_two: True
seed: 0

cache_dir: False

defaults:
  - configs/audio-config
  - configs/audio-cross-config
  - configs/bert-config
  - configs/cross-config
  - configs/decoder-config
  - configs/i3d-config
  - configs/visual-config
